application: desembarcodeltemplario
version: 2
runtime: python27
api_version: 1
threadsafe: false


handlers:
#Ruta del Server
- url: /api/.*
  script: server.main.APP
#Ruta del index
- url: (.*)/
  static_files: webapp/index.html
  upload: webapp
#Ruta de los Templates
- url: /view
  static_dir: webapp/view
#Ruta de las librerias de auxiliares
- url: /bower_components
  static_dir: bower_components
#Rutas de librerias de Notifaciones Push
- url: /manifest.json
  static_files: gamethriver/manifest.json
  upload: gamethriver

- url: /OneSignalSDKUpdaterWorker.js
  static_files: gamethriver/OneSignalSDKUpdaterWorker.js
  upload: gamethriver

- url: /OneSignalSDKWorker.js
  static_files: gamethriver/OneSignalSDKWorker.js
  upload: gamethriver

#Rutas de demas tipos de archivos
- url: (/.*\.js)
  static_files: webapp/js\1
  upload: webapp/js

- url: (/.*\.css)
  static_files: webapp/css\1
  upload: webapp/css

- url: (/.*\.woff)
  static_files: webapp/css\1
  upload: webapp/css

- url: (/.*\.ttf)
  static_files: webapp/css\1
  upload: webapp/css

- url: (/.*\.map)
  static_files: webapp/css\1
  upload: webapp/css

- url: (/.*\.ico)
  static_files: webapp/img\1
  upload: webapp/img

- url: (/.*\.gif)
  static_files: webapp/img\1
  upload: webapp/img

- url: (/.*\.jpg)
  static_files: webapp/img\1
  upload: webapp/img

- url: (/.*\.png)
  static_files: webapp/img\1
  upload: webapp/img

- url: (/.*\.svg)
  static_files: webapp/img\1
  upload: webapp/img
